const EmojiFy = (term: string): string => {
  return EMOJIS[term as keyof typeof EMOJIS] ?? ''
}

const EMOJIS = {
  COVID: '🦠',
  ['COVID-19']: '🦠',
  CORONAVIRUS: '🦠',
  PIC: '🖼',
  PHOTO: '🖼',
  PICTURE: '🖼',
  PICTURES: '🖼',
  NEWS: '📰',
  NUACHT: '📰',
  FOOTBALL: '⚽',
  SOCCER: '⚽',
  BOXING: '🥊',
  ENTERTAINMENT: '🎭',
  ALERT: '⚠',
  QUIZ: '⁉',
  HEALTH: '🧑‍⚕️',
  BUSINESS: '💼',
  HOME: '🏡',
  IRELAND: '🇮🇪',
  ['IRISH NEWS']: '🇮🇪',
  ['LOCAL NEWS']: '🇮🇪',
  ['NATIONAL NEWS']: '🇮🇪',
  WATCH: '🎞',
  VIDEO: '🎞',
  BASKETBALL: '🏀',
  BASEBALL: '⚾',
  VOLLEYBALL: '🏐',
  RUGBY: '🏉',
  TENNIS: '🎾',
  CRICKET: '🏏',
  GOLF: '⛳',
  LIFESTYLE: '🧜‍♂️',
  ['NORTHERN IRELAND']: '🇬🇧',
  ['NORTHERN IRELAND PREMIUM']: '🇬🇧',
  CELEBRITY: '🧜',
  ['CRIME & COURTS']: '🦹',
  CRIME: '🦹',
  WEATHER: '🌦',
  ['MEMORY LANE']: '🧓',
  BEEF: '🐂',
  ['HORSE RACING']: '🐎',
  SHEEP: '🐑',
  GAA: '🏐',
  COMMENT: '🙊',
  COMMUNITY: '❤',
}

export default EmojiFy
