import { Countries as CountryTypes } from '../types/countries';
import { LangTypes } from '../types';

interface Adjacents {
  countries: Array<CountryTypes | ''>;
  langs: Array<LangTypes | ''>;
}

export const ADJACENTS = new Map<CountryTypes, Adjacents>([
  [
    'oz',
    {
      countries: ['nz', 'to'],
      langs: ['en'],
    },
  ],
  [
    'ca',
    {
      countries: ['us', 'uk', 'fr', 'oz'],
      langs: ['fr', 'pl', 'es', 'de', 'it'],
    },
  ],
  [
    'in',
    {
      countries: ['pk', 'uk', 'qa', 'oz'],
      langs: ['hi', 'gu', 'ur', 'ta', 'bn'],
    },
  ],
  [
    'ie',
    {
      countries: ['oz', 'ca', 'us', 'nz'],
      langs: ['ga', 'pl', 'fr', 'es', 'de'],
    },
  ],
  [
    'nz',
    {
      countries: ['oz', 'ca', 'us', 'to'],
      langs: ['en'],
    },
  ],
  [
    'uk',
    {
      countries: ['ie', 'us', 'oz', 'ca'],
      langs: ['ga', 'en', 'pl', 'fr'],
    },
  ],
  [
    'us',
    {
      countries: ['ca', 'uk', 'oz', 'ie'],
      langs: ['en', 'es', 'fr'],
    },
  ],
  [
    'tz',
    {
      countries: ['za', 'zw', 'ng', 'ke'],
      langs: ['sw', 'en'],
    },
  ],
  [
    'zw',
    {
      countries: ['za', 'tz', 'ng', 'ke'],
      langs: ['en'],
    },
  ],
  [
    'ng',
    {
      countries: ['tz', 'zw', 'ke', 'gh'],
      langs: ['en', 'fr'],
    },
  ],
  [
    'ke',
    {
      countries: ['tz', 'zw', 'ug', 'so'],
      langs: ['sw', 'en'],
    },
  ],
  [
    'za',
    {
      countries: ['zw', 'tz', 'bw', 'na'],
      langs: ['en', 'sw'],
    },
  ],
  // ['gh', ['Ghana']],
  [
    'de',
    {
      countries: ['fr', 'it', 'pl'],
      langs: ['de', 'en', 'fr'],
    },
  ],
  [
    'fr',
    {
      countries: ['de', 'es', 'it'],
      langs: ['fr', 'en', 'es'],
    },
  ],
  [
    'es',
    {
      countries: ['fr', 'it'],
      langs: ['es', 'en'],
    },
  ],
  [
    'it',
    {
      countries: ['fr', 'es', 'de'],
      langs: ['it', 'en', 'fr'],
    },
  ],
  // ['nl', ['Netherlands']],
  // ['no', ['Norway']],
  // ['se', ['Sweden']],
  // ['dk', ['Denmark']],
  [
    'pl',
    {
      countries: ['de'],
      langs: ['pl', 'en', 'de'],
    },
  ],
  // ['ru', ['Russia']],
  [
    'cn',
    {
      countries: ['jp', 'kr'],
      langs: ['en'],
    },
  ],
  [
    'jp',
    {
      countries: ['cn', 'kr'],
      langs: ['ja', 'en'],
    },
  ],
  [
    'kr',
    {
      countries: ['cn', 'jp'],
      langs: ['ko', 'en'],
    },
  ],
  [
    'br',
    {
      countries: ['ar'],
      langs: ['pt', 'es'],
    },
  ],
  [
    'mx',
    {
      countries: ['us', 'es', 'ar'],
      langs: ['es', 'en'],
    },
  ],
  [
    'ar',
    {
      countries: ['br'],
      langs: ['es', 'pt'],
    },
  ],
  // ['co', ['Colombia']],
  // ['pe', ['Peru']],
  // ['ve', ['Venezuela']],
  // ['cl', ['Chile']],
  // ['ec', ['Ecuador']],
  // ['bo', ['Bolivia']],
  // ['py', ['Paraguay']],
  // ['uy', ['Uruguay']],
  // ['cr', ['Costa Rica']],
  // ['pa', ['Panama']],
  // ['cu', ['Cuba']],
  // ['do', ['Dominican Republic']],
  // ['gt', ['Guatemala']],
  // ['hn', ['Honduras']],
  // ['sv', ['El Salvador']],
  // ['bz', ['Belize']],
  // ['jm', ['Jamaica']],
  // ['ht', ['Haiti']],
  // ['ml', ['Mali']],
  // ['cg', ['Republic of the Congo']],
  // ['dz', ['Algeria']],
  // ['ly', ['Libya']],
  // ['sd', ['Sudan']],
  // ['ss', ['South Sudan']],
  // ['ne', ['Niger']],
  // ['my', ['Malaysia']],
  // ['sg', ['Singapore']],
  // ['th', ['Thailand']],
  // ['vn', ['Vietnam']],
  [
    'ph',
    {
      countries: ['id'],
      langs: ['tl', 'en'],
    },
  ],
  [
    'id',
    {
      countries: ['ph'],
      langs: ['id', 'en'],
    },
  ],
  // ['sa', ['Saudi Arabia']],
  [
    'ae',
    {
      countries: ['il', 'qa', 'kw'],
      langs: ['ar', 'en'],
    },
  ],
  [
    'il',
    {
      countries: ['ae', 'qa', 'kw', 'ps'],
      langs: ['he', 'ar', 'en'],
    },
  ],
  [
    'ps',
    {
      countries: ['ae', 'qa', 'kw', 'il'],
      langs: ['ar', 'en'],
    },
  ],
  // ['eg', ['Egypt']],
  // ['ma', ['Morocco']],
  // ['tn', ['Tunisia']],
  // ['ir', ['Iran']],
  [
    'pk',
    {
      countries: ['in', 'cn'],
      langs: ['ur', 'en'],
    },
  ],
  // ['lk', ['Sri Lanka']],
  // ['np', ['Nepal']],
  // ['bt', ['Bhutan']],
  // ['mm', ['Myanmar']],
  // ['kh', ['Cambodia']],
  // ['la', ['Laos']],
  // ['mn', ['Mongolia']],
  // ['kz', ['Kazakhstan']],
  // ['tm', ['Turkmenistan']],
  // ['tj', ['Tajikistan']],
  // ['az', ['Azerbaijan']],
  // ['tr', ['Turkey']],
  // ['gr', ['Greece']],
  // ['pt', ['Portugal']],
  // ['hu', ['Hungary']],
  // ['cz', ['Czech Republic']],
  // ['sk', ['Slovakia']],
  // ['at', ['Austria']],
  // ['ch', ['Switzerland']],
  // ['be', ['Belgium']],
  // ['lu', ['Luxembourg']],
  // ['is', ['Iceland']],
  // ['fi', ['Finland']],
  // ['ba', ['Bosnia and Herzegovina']],
  // ['bg', ['Bulgaria']],
  // ['hr', ['Croatia']],
  // ['cy', ['Cyprus']],
  // ['ee', ['Estonia']],
  // ['lv', ['Latvia']],
  // ['lt', ['Lithuania']],
  // ['mt', ['Malta']],
  // ['ro', ['Romania']],
  // ['si', ['Slovenia']],
  // ['rs', ['Serbia']],
  // ['me', ['Montenegro']],
  // ['mk', ['North Macedonia']],
  // ['al', ['Albania']],
  // ['by', ['Belarus']],
  // ['ua', ['Ukraine']],
  // ['md', ['Moldova']],
  // ['ge', ['Georgia']],
  // ['am', ['Armenia']],
  // ['uz', ['Uzbekistan']],
  // ['kg', ['Kyrgyzstan']],
  // ['af', ['Afghanistan']],
  // ['bt', ['Bhutan']],
  // ['bd', ['Bangladesh']],
  // ['mv', ['Maldives']],
  // ['iq', ['Iraq']],
  // ['sy', ['Syria']],
  // ['lb', ['Lebanon']],
  // ['jo', ['Jordan']],
  [
    'kw',
    {
      countries: ['il', 'ae', 'qa'],
      langs: ['ar', 'en'],
    },
  ],
  [
    'qa',
    {
      countries: ['il', 'ae', 'kw'],
      langs: ['ar', 'en'],
    },
  ],
  // ['bh', ['Bahrain']],
  // ['om', ['Oman']],
  // ['ye', ['Yemen']],
  // ['sd', ['Sudan']],
  // ['ss', ['South Sudan']],
  // ['cf', ['Central African Republic']],
  // ['cm', ['Cameroon']],
  // ['td', ['Chad']],
  // ['gq', ['Equatorial Guinea']],
  // ['ga', ['Gabon']],
  // ['st', ['Sao Tome and Principe']],
  // ['cg', ['Republic of the Congo']],
  // ['cd', ['Democratic Republic of the Congo']],
  // ['ao', ['Angola']],
  // ['na', ['Namibia']],
  // ['bw', ['Botswana']],
  // ['zm', ['Zambia']],
  // ['mw', ['Malawi']],
  // ['mg', ['Madagascar']],
  // ['sc', ['Seychelles']],
  // ['mu', ['Mauritius']],
  // ['km', ['Comoros']],
  // ['rw', ['Rwanda']],
  // ['bi', ['Burundi']],
  // ['ug', ['Uganda']],
  // ['tz', ['Tanzania']],
  // ['so', ['Somalia']],
  // ['et', ['Ethiopia']],
  // ['er', ['Eritrea']],
  // ['dj', ['Djibouti']],
  // ['ls', ['Lesotho']],
  // ['mz', ['Mozambique']],
  // ['ls', ['Lesotho']],
  // ['sz', ['Eswatini']],
  // ['km', ['Comoros']],
  // ['ni', ['Nicaragua']],
  // ['ad', ['Andorra']],
  // ['ag', ['Antigua and Barbuda']],
  // ['bb', ['Barbados']],
  // ['bs', ['Bahamas']],
  // ['cv', ['Cabo Verde']],
  // ['dm', ['Dominica']],
  // ['fj', ['Fiji']],
  // ['gd', ['Grenada']],
  // ['gy', ['Guyana']],
  // ['ki', ['Kiribati']],
  // ['kn', ['Saint Kitts and Nevis']],
  // ['lc', ['Saint Lucia']],
  // ['nr', ['Nauru']],
  // ['sb', ['Solomon Islands']],
  // ['sl', ['Sierra Leone']],
  // ['sr', ['Suriname']],
  [
    'to',
    {
      countries: ['oz', 'nz'],
      langs: ['en'],
    },
  ],
  // ['tt', ['Trinidad and Tobago']],
  // ['tv', ['Tuvalu']],
  // ['vu', ['Vanuatu']],
  // ['ws', ['Samoa']],
  // ['vc', ['Saint Vincent and the Grenadines']],
]);
