import { Countries as CountryTypes } from '../types/countries';

export const NEIGHBOURS = new Map<CountryTypes, Array<CountryTypes | ''>>([
  ['oz', ['nz', 'to']],
  ['ca', ['']],
  ['in', ['pk']],
  ['ie', ['uk']],
  ['nz', ['oz', 'to']],
  ['uk', ['']],
  ['us', ['ca']],
  ['tz', ['za', 'zw', 'ng', 'ke']],
  ['zw', ['za', 'tz', 'ng', 'ke']],
  ['za', ['tz', 'zw', 'ng', 'ke']],
  ['ng', ['za', 'zw', 'tz', 'ke']],
  ['ke', ['za', 'zw', 'ng', 'tz']],
  // ['gh', ['Ghana']],
  ['de', ['fr', 'it', 'pl']],
  ['fr', ['de', 'es', 'it']],
  ['es', ['fr', 'it']],
  ['it', ['fr', 'es', 'de']],
  // ['nl', ['Netherlands']],
  // ['no', ['Norway']],
  // ['se', ['Sweden']],
  // ['dk', ['Denmark']],
  ['pl', ['de']],
  // ['ru', ['Russia']],
  ['cn', ['jp', 'kr']],
  ['jp', ['cn', 'kr']],
  ['kr', ['cn', 'jp']],
  ['br', ['ar']],
  ['mx', ['us', 'es', 'ar']],
  ['ar', ['br']],
  // ['co', ['Colombia']],
  // ['pe', ['Peru']],
  // ['ve', ['Venezuela']],
  // ['cl', ['Chile']],
  // ['ec', ['Ecuador']],
  // ['bo', ['Bolivia']],
  // ['py', ['Paraguay']],
  // ['uy', ['Uruguay']],
  // ['cr', ['Costa Rica']],
  // ['pa', ['Panama']],
  // ['cu', ['Cuba']],
  // ['do', ['Dominican Republic']],
  // ['gt', ['Guatemala']],
  // ['hn', ['Honduras']],
  // ['sv', ['El Salvador']],
  // ['bz', ['Belize']],
  // ['jm', ['Jamaica']],
  // ['ht', ['Haiti']],
  // ['ml', ['Mali']],
  // ['cg', ['Republic of the Congo']],
  // ['dz', ['Algeria']],
  // ['ly', ['Libya']],
  // ['sd', ['Sudan']],
  // ['ss', ['South Sudan']],
  // ['ne', ['Niger']],
  // ['my', ['Malaysia']],
  // ['sg', ['Singapore']],
  // ['th', ['Thailand']],
  // ['vn', ['Vietnam']],
  ['ph', ['id']],
  ['id', ['ph']],
  // ['sa', ['Saudi Arabia']],
  ['ae', ['il', 'qa', 'kw']],
  ['il', ['ae', 'qa', 'kw']],
  // ['eg', ['Egypt']],
  // ['ma', ['Morocco']],
  // ['tn', ['Tunisia']],
  // ['ir', ['Iran']],
  ['pk', ['in', 'cn']],
  // ['lk', ['Sri Lanka']],
  // ['np', ['Nepal']],
  // ['bt', ['Bhutan']],
  // ['mm', ['Myanmar']],
  // ['kh', ['Cambodia']],
  // ['la', ['Laos']],
  // ['mn', ['Mongolia']],
  // ['kz', ['Kazakhstan']],
  // ['tm', ['Turkmenistan']],
  // ['tj', ['Tajikistan']],
  // ['az', ['Azerbaijan']],
  // ['tr', ['Turkey']],
  // ['gr', ['Greece']],
  // ['pt', ['Portugal']],
  // ['hu', ['Hungary']],
  // ['cz', ['Czech Republic']],
  // ['sk', ['Slovakia']],
  // ['at', ['Austria']],
  // ['ch', ['Switzerland']],
  // ['be', ['Belgium']],
  // ['lu', ['Luxembourg']],
  // ['is', ['Iceland']],
  // ['fi', ['Finland']],
  // ['ba', ['Bosnia and Herzegovina']],
  // ['bg', ['Bulgaria']],
  // ['hr', ['Croatia']],
  // ['cy', ['Cyprus']],
  // ['ee', ['Estonia']],
  // ['lv', ['Latvia']],
  // ['lt', ['Lithuania']],
  // ['mt', ['Malta']],
  // ['ro', ['Romania']],
  // ['si', ['Slovenia']],
  // ['rs', ['Serbia']],
  // ['me', ['Montenegro']],
  // ['mk', ['North Macedonia']],
  // ['al', ['Albania']],
  // ['by', ['Belarus']],
  // ['ua', ['Ukraine']],
  // ['md', ['Moldova']],
  // ['ge', ['Georgia']],
  // ['am', ['Armenia']],
  // ['uz', ['Uzbekistan']],
  // ['kg', ['Kyrgyzstan']],
  // ['af', ['Afghanistan']],
  // ['bt', ['Bhutan']],
  // ['bd', ['Bangladesh']],
  // ['mv', ['Maldives']],
  // ['iq', ['Iraq']],
  // ['sy', ['Syria']],
  // ['lb', ['Lebanon']],
  // ['jo', ['Jordan']],
  ['kw', ['il', 'ae', 'qa']],
  ['qa', ['il', 'ae', 'kw']],
  // ['bh', ['Bahrain']],
  // ['om', ['Oman']],
  // ['ye', ['Yemen']],
  // ['sd', ['Sudan']],
  // ['ss', ['South Sudan']],
  // ['cf', ['Central African Republic']],
  // ['cm', ['Cameroon']],
  // ['td', ['Chad']],
  // ['gq', ['Equatorial Guinea']],
  // ['ga', ['Gabon']],
  // ['st', ['Sao Tome and Principe']],
  // ['cg', ['Republic of the Congo']],
  // ['cd', ['Democratic Republic of the Congo']],
  // ['ao', ['Angola']],
  // ['na', ['Namibia']],
  // ['bw', ['Botswana']],
  // ['zm', ['Zambia']],
  // ['mw', ['Malawi']],
  // ['mg', ['Madagascar']],
  // ['sc', ['Seychelles']],
  // ['mu', ['Mauritius']],
  // ['km', ['Comoros']],
  // ['rw', ['Rwanda']],
  // ['bi', ['Burundi']],
  // ['ug', ['Uganda']],
  // ['tz', ['Tanzania']],
  // ['so', ['Somalia']],
  // ['et', ['Ethiopia']],
  // ['er', ['Eritrea']],
  // ['dj', ['Djibouti']],
  // ['ls', ['Lesotho']],
  // ['mz', ['Mozambique']],
  // ['ls', ['Lesotho']],
  // ['sz', ['Eswatini']],
  // ['km', ['Comoros']],
  // ['ni', ['Nicaragua']],
  // ['ad', ['Andorra']],
  // ['ag', ['Antigua and Barbuda']],
  // ['bb', ['Barbados']],
  // ['bs', ['Bahamas']],
  // ['cv', ['Cabo Verde']],
  // ['dm', ['Dominica']],
  // ['fj', ['Fiji']],
  // ['gd', ['Grenada']],
  // ['gy', ['Guyana']],
  // ['ki', ['Kiribati']],
  // ['kn', ['Saint Kitts and Nevis']],
  // ['lc', ['Saint Lucia']],
  // ['nr', ['Nauru']],
  // ['sb', ['Solomon Islands']],
  // ['sl', ['Sierra Leone']],
  // ['sr', ['Suriname']],
  ['to', ['oz', 'nz']],
  // ['tt', ['Trinidad and Tobago']],
  // ['tv', ['Tuvalu']],
  // ['vu', ['Vanuatu']],
  // ['ws', ['Samoa']],
  // ['vc', ['Saint Vincent and the Grenadines']],
]);
