export const NS_BI_MAP = new Map([
  ['CA_LDVR', 'Le Devoir'],
  ['Le Devoir', 'CA_LDVR'],
  ['CA_QCTO', 'The Quebec Chronicle Telegraph'],
  ['The Quebec Chronicle Telegraph', 'CA_QCTO'],
  ['CA_TRTS', 'Toronto Star'],
  ['Toronto Star', 'CA_TRTS'],
  ['CA_TGAM', 'The Globe And Mail'],
  ['The Globe And Mail', 'CA_TGAM'],
  ['CA_LPRS', 'La Presse'],
  ['La Presse', 'CA_LPRS'],
  ['CA_JMTL', 'Le Journal de Montréal'],
  ['Le Journal de Montréal', 'CA_JMTL'],
  ['CA_MTGZ', 'Montreal Gazette'],
  ['Montreal Gazette', 'CA_MTGZ'],
  ['CA_VSUN', 'Vancouver Sun'],
  ['Vancouver Sun', 'CA_VSUN'],
  ['CA_TPRV', 'The Province'],
  ['The Province', 'CA_TPRV'],
  ['CA_NPST', 'National Post'],
  ['National Post', 'CA_NPST'],
  ['CA_CLHD', 'Calgary Herald'],
  ['Calgary Herald', 'CA_CLHD'],
  ['CA_OTCZ', 'Ottawa Citizen'],
  ['Ottawa Citizen', 'CA_OTCZ'],
  ['CA_EDJL', 'Edmonton Journal'],
  ['Edmonton Journal', 'CA_EDJL'],
  ['CA_TSUN', 'Toronto Sun'],
  ['Toronto Sun', 'CA_TSUN'],
  ['CA_LSOL', 'Le Soleil'],
  ['Le Soleil', 'CA_LSOL'],
  ['CA_SPEC', 'The Hamilton Spectator'],
  ['The Hamilton Spectator', 'CA_SPEC'],
  ['CA_TCOL', 'The Times Colonist'],
  ['The Times Colonist', 'CA_TCOL'],
  ['CA_LFRP', 'The London Free Press'],
  ['The London Free Press', 'CA_LFRP'],
  ['CA_WNST', 'Windsor Star'],
  ['Windsor Star', 'CA_WNST'],
  ['CA_EDSN', 'Edmonton Sun'],
  ['Edmonton Sun', 'CA_EDSN'],
  ['CA_TREC', 'Waterloo Region Record'],
  ['Waterloo Region Record', 'CA_TREC'],
  ['CA_SPHX', 'The StarPhoenix'],
  ['The StarPhoenix', 'CA_SPHX'],
  ['CA_CSUN', 'Calgary Sun'],
  ['Calgary Sun', 'CA_CSUN'],
  ['CA_RLPT', 'Regina Leader-Post'],
  ['Regina Leader-Post', 'CA_RLPT'],
  ['CA_LCDS', 'Le Courrier du Sud'],
  ['Le Courrier du Sud', 'CA_LCDS'],
  ['CA_NIND', 'CanIndia News'],
  ['CanIndia News', 'CA_NIND'],
  ['CA_TCJN', 'The Canadian Jewish News'],
  ['The Canadian Jewish News', 'CA_TCJN'],
  ['CA_CORR', 'Corriere Canadese'],
  ['Corriere Canadese', 'CA_CORR'],
  ['CA_HRZN', 'Horizon Weekly'],
  ['Horizon Weekly', 'CA_HRZN'],
  ['CA_KRTM', 'The Korea Times Daily'],
  ['The Korea Times Daily', 'CA_KRTM'],
  ['CA_BJST', 'Bejsment'],
  ['Bejsment', 'CA_BJST'],
  ['CA_RSEX', 'The Russian Express Weekly Newspaper'],
  ['The Russian Express Weekly Newspaper', 'CA_RSEX'],
  ['CA_SLMT', 'Salam Toronto'],
  ['Salam Toronto', 'CA_SLMT'],
  ['CA_BNGT', 'Bengali Times'],
  ['Bengali Times', 'CA_BNGT'],
  ['CA_TCST', 'The Coast'],
  ['The Coast', 'CA_TCST'],
  ['CA_STRT', 'The Grapevine'],
  ['The Grapevine', 'CA_STRT'],
  ['CA_NWMG', 'NOW Magazine'],
  ['NOW Magazine', 'CA_NWMG'],
  ['IE_AGRI', 'Agriland'],
  ['Agriland', 'IE_AGRI'],
  ['IE_AADV', 'Athlone Advertiser'],
  ['Athlone Advertiser', 'IE_AADV'],
  ['IE_BLLS', 'BALLS.ie'],
  ['BALLS.ie', 'IE_BLLS'],
  ['IE_BEAT', 'Beat 102 103'],
  ['Beat 102 103', 'IE_BEAT'],
  ['IE_BLFT', 'Belfast Telegraph'],
  ['Belfast Telegraph', 'IE_BLFT'],
  ['IE_BZPL', 'Biz Plus'],
  ['Biz Plus', 'IE_BZPL'],
  ['IE_BRKN', 'breakingnews.ie'],
  ['breakingnews.ie', 'IE_BRKN'],
  ['IE_BUZZ', 'Buzz'],
  ['Buzz', 'IE_BUZZ'],
  ['IE_CLWL', 'Carlow Live'],
  ['Carlow Live', 'IE_CLWL'],
  ['IE_CLFM', 'Clare FM'],
  ['Clare FM', 'IE_CLFM'],
  ['IE_CLRL', 'Clare Live'],
  ['Clare Live', 'IE_CLRL'],
  ['IE_CLHT', 'Classic Hits'],
  ['Classic Hits', 'IE_CLHT'],
  ['IE_COLC', 'Coleraine Chronicle'],
  ['Coleraine Chronicle', 'IE_COLC'],
  ['IE_CTRB', 'Connacht Tribune'],
  ['Connacht Tribune', 'IE_CTRB'],
  ['IE_CRKB', 'Cork Beo'],
  ['Cork Beo', 'IE_CRKB'],
  ['IE_CRKI', 'Cork Independent'],
  ['Cork Independent', 'IE_CRKI'],
  ['IE_RDFM', "Cork's RedFM"],
  ["Cork's RedFM", 'IE_RDFM'],
  ['IE_DERJ', 'Derry Journal'],
  ['Derry Journal', 'IE_DERJ'],
  ['IE_DRYN', 'Derry Now'],
  ['Derry Now', 'IE_DRYN'],
  ['IE_DLDY', 'Donegal Daily'],
  ['Donegal Daily', 'IE_DLDY'],
  ['IE_DNGL', 'Donegal Live'],
  ['Donegal Live', 'IE_DNGL'],
  ['IE_DLNW', 'Donegal News / Derry People'],
  ['Donegal News / Derry People', 'IE_DLNW'],
  ['IE_DINQ', 'Dublin Inquirer'],
  ['Dublin Inquirer', 'IE_DINQ'],
  ['IE_DLIV', 'Dublin Live'],
  ['Dublin Live', 'IE_DLIV'],
  ['IE_DNEW', 'Dublin News'],
  ['Dublin News', 'IE_DNEW'],
  ['IE_DNPP', 'Dublin People'],
  ['Dublin People', 'IE_DNPP'],
  ['IE_98FM', "Dublin's 98FM"],
  ["Dublin's 98FM", 'IE_98FM'],
  ['IE_DLKD', 'Dundalk Democrat'],
  ['Dundalk Democrat', 'IE_DLKD'],
  ['IE_ESTC', 'East Coast FM'],
  ['East Coast FM', 'IE_ESTC'],
  ['IE_ECHL', 'Echo Live'],
  ['Echo Live', 'IE_ECHL'],
  ['IE_ENGI', 'Engineers Ireland'],
  ['Engineers Ireland', 'IE_ENGI'],
  ['IE_ENTR', 'entertainment.ie'],
  ['entertainment.ie', 'IE_ENTR'],
  ['IE_EVOK', 'EVOKE'],
  ['EVOKE', 'IE_EVOK'],
  ['IE_EXTR', 'Extra.ie'],
  ['Extra.ie', 'IE_EXTR'],
  ['IE_FERH', 'Fermanagh Herald'],
  ['Fermanagh Herald', 'IE_FERH'],
  ['IE_FLT', 'Fleet Transport'],
  ['Fleet Transport', 'IE_FLT'],
  ['IE_F104', 'FM104'],
  ['FM104', 'IE_F104'],
  ['IE_GLFE', 'Gaelic Life'],
  ['Gaelic Life', 'IE_GLFE'],
  ['IE_GBFM', 'Galway Bay FM'],
  ['Galway Bay FM', 'IE_GBFM'],
  ['IE_GADV', 'Galway Advertiser'],
  ['Galway Advertiser', 'IE_GADV'],
  ['IE_GBEO', 'Galway Beo'],
  ['Galway Beo', 'IE_GBEO'],
  ['IE_GDLY', 'Galway Daily'],
  ['Galway Daily', 'IE_GDLY'],
  ['IE_GCN', 'Gay Community News'],
  ['Gay Community News', 'IE_GCN'],
  ['IE_HER', 'Her'],
  ['Her', 'IE_HER'],
  ['IE_HGV', 'HGV Ireland'],
  ['HGV Ireland', 'IE_HGV'],
  ['IE_HIRD', 'Highland Radio'],
  ['Highland Radio', 'IE_HIRD'],
  ['IE_HOTP', 'Hot Press'],
  ['Hot Press', 'IE_HOTP'],
  ['IE_HSHM', 'House And Home'],
  ['House And Home', 'IE_HSHM'],
  ['IE_IMG', 'Image'],
  ['Image', 'IE_IMG'],
  ['IE_IOWI', 'Inishowen Independent'],
  ['Inishowen Independent', 'IE_IOWI'],
  ['IE_IRAD', 'iRadio'],
  ['iRadio', 'IE_IRAD'],
  ['IE_BOX', 'Irish Boxing'],
  ['Irish Boxing', 'IE_BOX'],
  ['IE_CNTR', 'IrishCentral'],
  ['IrishCentral', 'IE_CNTR'],
  ['IE_CTRM', 'Irish Country Magazine'],
  ['Irish Country Magazine', 'IE_CTRM'],
  ['IE_EXAM', 'Irish Examiner'],
  ['Irish Examiner', 'IE_EXAM'],
  ['IE_FARM', 'Irish Farmers Journal'],
  ['Irish Farmers Journal', 'IE_FARM'],
  ['IE_LEGL', 'Irish Legal News'],
  ['Irish Legal News', 'IE_LEGL'],
  ['IE_IMT', 'Irish Medical Times'],
  ['Irish Medical Times', 'IE_IMT'],
  ['IE_MIRR', 'Irish Mirror'],
  ['Irish Mirror', 'IE_MIRR'],
  ['IE_JOE', 'Joe.ie'],
  ['Joe.ie', 'IE_JOE'],
  ['IE_KCLR', 'KCLR 96FM'],
  ['KCLR 96FM', 'IE_KCLR'],
  ['IE_KFMR', 'Kfm'],
  ['Kfm', 'IE_KFMR'],
  ['IE_KDRN', 'Kildare Nationalist'],
  ['Kildare Nationalist', 'IE_KDRN'],
  ['IE_KLDN', 'Kildare Now'],
  ['Kildare Now', 'IE_KLDN'],
  ['IE_KILP', 'Kilkenny People'],
  ['Kilkenny People', 'IE_KILP'],
  ['IE_KLRT', 'Killarney Today'],
  ['Killarney Today', 'IE_KLRT'],
  ['IE_LISN', 'Laois Nationalist'],
  ['Laois Nationalist', 'IE_LISN'],
  ['IE_LAW', 'Law Society Gazette'],
  ['Law Society Gazette', 'IE_LAW'],
  ['IE_LNEX', 'Leinster Express'],
  ['Leinster Express', 'IE_LNEX'],
  ['IE_LNLD', 'Leinster Leader'],
  ['Leinster Leader', 'IE_LNLD'],
  ['IE_LTRO', 'Leitrim Observer'],
  ['Leitrim Observer', 'IE_LTRO'],
  ['IE_LIML', 'Limerick Leader'],
  ['Limerick Leader', 'IE_LIML'],
  ['IE_LIMP', 'Limerick Post'],
  ['Limerick Post', 'IE_LIMP'],
  ['IE_95FM', 'Live 95'],
  ['Live 95', 'IE_95FM'],
  ['IE_LMFM', 'LMFM'],
  ['LMFM', 'IE_LMFM'],
  ['IE_LNGL', 'Longford Leader'],
  ['Longford Leader', 'IE_LNGL'],
  ['IE_MADV', 'Mayo Adevertiser'],
  ['Mayo Adevertiser', 'IE_MADV'],
  ['IE_MYNW', 'Mayo News'],
  ['Mayo News', 'IE_MYNW'],
  ['IE_MTHC', 'Meath Chronicle'],
  ['Meath Chronicle', 'IE_MTHC'],
  ['IE_MRST', 'Merrion Street'],
  ['Merrion Street', 'IE_MRST'],
  ['IE_M103', 'Midlands 103'],
  ['Midlands 103', 'IE_M103'],
  ['IE_MIDW', 'MidWest Radio'],
  ['MidWest Radio', 'IE_MIDW'],
  ['IE_MTLY', 'Motley'],
  ['Motley', 'IE_MTLY'],
  ['IE_NNGG', 'Nenagh Guardian'],
  ['Nenagh Guardian', 'IE_NNGG'],
  ['IE_NNGL', 'Nenagh Live'],
  ['Nenagh Live', 'IE_NNGL'],
  ['IE_NLTR', 'The News Letter'],
  ['The News Letter', 'IE_NLTR'],
  ['IE_NTLK', 'newstalk'],
  ['newstalk', 'IE_NTLK'],
  ['IE_NSND', 'Northern Sound'],
  ['Northern Sound', 'IE_NSND'],
  ['IE_NSTD', 'Northern Standard'],
  ['Northern Standard', 'IE_NSTD'],
  ['IE_NOTE', 'Noteworthy'],
  ['Noteworthy', 'IE_NOTE'],
  ['IE_TG4', 'Nuacht TG4'],
  ['Nuacht TG4', 'IE_TG4'],
  ['IE_OCEN', 'Ocean FM'],
  ['Ocean FM', 'IE_OCEN'],
  ['IE_OFYE', 'Offaly Express'],
  ['Offaly Express', 'IE_OFYE'],
  ['IE_OFFI', 'Offaly Independent'],
  ['Offaly Independent', 'IE_OFFI'],
  ['IE_OTBS', 'Off The Ball Sports'],
  ['Off The Ball Sports', 'IE_OTBS'],
  ['IE_PNDT', 'Pundit Arena'],
  ['Pundit Arena', 'IE_PNDT'],
  ['IE_NOVA', 'Radio Nova'],
  ['Radio Nova', 'IE_NOVA'],
  ['IE_RKER', 'Radio Kerry'],
  ['Radio Kerry', 'IE_RKER'],
  ['IE_RLCT', 'RollerCoaster.ie'],
  ['RollerCoaster.ie', 'IE_RLCT'],
  ['IE_ROSH', 'Roscommon Herald'],
  ['Roscommon Herald', 'IE_ROSH'],
  ['IE_RSVP', 'RSVP Live'],
  ['RSVP Live', 'IE_RSVP'],
  ['IE_SNNS', 'Shannonside FM'],
  ['Shannonside FM', 'IE_SNNS'],
  ['IE_SLCN', 'Siliconrepublic.com'],
  ['Siliconrepublic.com', 'IE_SLCN'],
  ['IE_SLGW', 'Sligo Weekender'],
  ['Sligo Weekender', 'IE_SLGW'],
  ['IE_SERD', 'South East Radio'],
  ['South East Radio', 'IE_SERD'],
  ['IE_SPIN', 'SPIN 1038'],
  ['SPIN 1038', 'IE_SPIN'],
  ['IE_SPRT', 'Spirit Radio'],
  ['Spirit Radio', 'IE_SPRT'],
  ['IE_SJOE', 'Sports Joe'],
  ['Sports Joe', 'IE_SJOE'],
  ['IE_SUNW', 'Sunday World'],
  ['Sunday World', 'IE_SUNW'],
  ['IE_TECC', 'Tech Central'],
  ['Tech Central', 'IE_TECC'],
  ['IE_ANGC', 'The Anglo Celt'],
  ['The Anglo Celt', 'IE_ANGC'],
  ['IE_AVNP', 'The Avondhu Press'],
  ['The Avondhu Press', 'IE_AVNP'],
  ['IE_BIZP', 'The Business Post'],
  ['The Business Post', 'IE_BIZP'],
  ['IE_CLRC', 'The Clare Champion'],
  ['The Clare Champion', 'IE_CLRC'],
  ['IE_CLRE', 'The Clare Echo'],
  ['The Clare Echo', 'IE_CLRE'],
  ['IE_CONT', 'The Connaught Telegraph'],
  ['The Connaught Telegraph', 'IE_CONT'],
  ['IE_INDO', 'Irish Independent'],
  ['Irish Independent', 'IE_INDO'],
  ['IE_ARGS', 'The Argus'],
  ['The Argus', 'IE_ARGS'],
  ['IE_CRKM', 'The Corkman'],
  ['The Corkman', 'IE_CRKM'],
  ['IE_FNGL', 'Fingal Independent'],
  ['Fingal Independent', 'IE_FNGL'],
  ['IE_GORY', 'Gorey Guardian'],
  ['Gorey Guardian', 'IE_GORY'],
  ['IE_NWRS', 'New Ross Standard'],
  ['New Ross Standard', 'IE_NWRS'],
  ['IE_SSTR', 'The Southern Star'],
  ['The Southern Star', 'IE_SSTR'],
  ['IE_STRW', 'Strabane Weekly News and Tyrone & Donegal Reporter'],
  ['Strabane Weekly News and Tyrone & Donegal Reporter', 'IE_STRW'],
  ['IE_TYCN', 'The Tyrone Constitution'],
  ['The Tyrone Constitution', 'IE_TYCN'],
  ['IE_ULGZ', 'Ulster Gazette and Armagh Standard'],
  ['Ulster Gazette and Armagh Standard', 'IE_ULGZ'],
  ['IE_WCRK', 'West Cork People'],
  ['West Cork People', 'IE_WCRK'],
  ['IE_INIE', 'Inside Ireland'],
  ['Inside Ireland', 'IE_INIE'],
  ['IE_KLAD', 'Killarney Advertiser'],
  ['Killarney Advertiser', 'IE_KLAD'],
  ['IE_LBRT', 'The Liberty'],
  ['The Liberty', 'IE_LBRT'],
  ['IE_NEWD', 'Newry Democrat'],
  ['Newry Democrat', 'IE_NEWD'],
  ['IE_NEWR', 'Newry.ie'],
  ['Newry.ie', 'IE_NEWR'],
  ['IE_NG24', 'Nasz Głos'],
  ['Nasz Głos', 'IE_NG24'],
  ['IE_GLSS', 'The Gloss'],
  ['The Gloss', 'IE_GLSS'],
  ['IE_IMPR', 'The Impartial Reporter'],
  ['The Impartial Reporter', 'IE_IMPR'],
  ['IE_ECHO', 'The Irish Echo'],
  ['The Irish Echo', 'IE_ECHO'],
  ['IE_FELD', 'The Irish Field'],
  ['The Irish Field', 'IE_FELD'],
  ['IE_NEWS', 'The Irish News'],
  ['The Irish News', 'IE_NEWS'],
  ['IE_POST', 'The Irish Post'],
  ['The Irish Post', 'IE_POST'],
  ['IE_TIME', 'The Irish Times'],
  ['The Irish Times', 'IE_TIME'],
  ['IE_WRLD', 'The Irish World'],
  ['The Irish World', 'IE_WRLD'],
  ['IE_JRNL', 'TheJournal.ie'],
  ['TheJournal.ie', 'IE_JRNL'],
  ['IE_KRYM', 'The Kerryman'],
  ['The Kerryman', 'IE_KRYM'],
  ['IE_MUNX', 'The Munster Express'],
  ['The Munster Express', 'IE_MUNX'],
  ['IE_CLWN', 'The Nationalist'],
  ['The Nationalist', 'IE_CLWN'],
  ['IE_SLGC', 'The Sligo Champion'],
  ['The Sligo Champion', 'IE_SLGC'],
  ['IE_TMHD', 'The Tuam Herald'],
  ['The Tuam Herald', 'IE_TMHD'],
  ['IE_WXFP', 'The Wexford People'],
  ['The Wexford People', 'IE_WXFP'],
  ['IE_WKWP', 'The Wicklow People'],
  ['The Wicklow People', 'IE_WKWP'],
  ['IE_42', 'The 42'],
  ['The 42', 'IE_42'],
  ['IE_TIPL', 'Tipperary Live'],
  ['Tipperary Live', 'IE_TIPL'],
  ['IE_TN2', 'TN2 Magazine'],
  ['TN2 Magazine', 'IE_TN2'],
  ['IE_TRTY', 'Trinity News'],
  ['Trinity News', 'IE_TRTY'],
  ['IE_TRSC', 'Tuairisc'],
  ['Tuairisc', 'IE_TRSC'],
  ['IE_TYRC', 'Tyrone Courier'],
  ['Tyrone Courier', 'IE_TYRC'],
  ['IE_UCEX', 'University Express'],
  ['University Express', 'IE_UCEX'],
  ['IE_UNOB', 'University Observer'],
  ['University Observer', 'IE_UNOB'],
  ['IE_UNIT', 'University Times'],
  ['University Times', 'IE_UNIT'],
  ['IE_VLGE', 'Village Magazine'],
  ['Village Magazine', 'IE_VLGE'],
  ['IE_WTRL', 'Waterford Live'],
  ['Waterford Live', 'IE_WTRL'],
  ['IE_WTRN', 'Waterford News & Star'],
  ['Waterford News & Star', 'IE_WTRN'],
  ['IE_WSTX', 'Westmeath Examiner'],
  ['Westmeath Examiner', 'IE_WSTX'],
  ['IE_WSTI', 'Westmeath Independent'],
  ['Westmeath Independent', 'IE_WSTI'],
  ['IE_WSTR', 'Western People'],
  ['Western People', 'IE_WSTR'],
  ['IE_WLFM', 'WLR FM'],
  ['WLR FM', 'IE_WLFM'],
  ['IE_WW', 'Womans Way'],
  ['Womans Way', 'IE_WW'],
  ['IE_RTE', 'RTÉ'],
  ['RTÉ', 'IE_RTE'],
  ['IE_DTCH', 'The Ditch'],
  ['The Ditch', 'IE_DTCH'],
  ['IE_EBEO', 'Éire Bheo'],
  ['Éire Bheo', 'IE_EBEO'],
  ['IN_BYSC', 'Bombay Samachar'],
  ['Bombay Samachar', 'IN_BYSC'],
  ['IN_TPNR', 'The Pioneer'],
  ['The Pioneer', 'IN_TPNR'],
  ['IN_THND', 'The Hindu'],
  ['The Hindu', 'IN_THND'],
  ['IN_HST', 'Hindustan Times'],
  ['Hindustan Times', 'IN_HST'],
  ['IN_IXPR', 'The Indian Express'],
  ['The Indian Express', 'IN_IXPR'],
  ['IN_DHRL', 'Deccan Herald'],
  ['Deccan Herald', 'IN_DHRL'],
  ['IN_TLGP', 'The Telegraph'],
  ['The Telegraph', 'IN_TLGP'],
  ['IN_DNA', 'Daily News & Analysis'],
  ['Daily News & Analysis', 'IN_DNA'],
  ['IN_DNCH', 'Deccan Chronicle'],
  ['Deccan Chronicle', 'IN_DNCH'],
  ['IN_NVHT', 'The Navhind Times'],
  ['The Navhind Times', 'IN_NVHT'],
  ['IN_AAGE', 'The Asian Age'],
  ['The Asian Age', 'IN_AAGE'],
  ['IN_BIZS', 'Business Standard'],
  ['Business Standard', 'IN_BIZS'],
  ['IN_HBIZ', 'हिंदी बिजनेस स्टैंडर्ड'],
  ['हिंदी बिजनेस स्टैंडर्ड', 'IN_HBIZ'],
  ['IN_ECOT', 'The Economic Times'],
  ['The Economic Times', 'IN_ECOT'],
  ['IN_TIMS', 'India Times'],
  ['India Times', 'IN_TIMS'],
  ['IN_FEXP', 'Financial Express'],
  ['Financial Express', 'IN_FEXP'],
  ['IN_NIEX', 'The New Indian Express'],
  ['The New Indian Express', 'IN_NIEX'],
  ['IN_MINT', 'Mint'],
  ['Mint', 'IN_MINT'],
  ['IN_GSMC', 'ગુજરાત સમાચાર'],
  ['ગુજરાત સમાચાર', 'IN_GSMC'],
  ['IN_TRBI', 'The Tribune'],
  ['The Tribune', 'IN_TRBI'],
  ['UK_MIRR', 'The Mirror'],
  ['The Mirror', 'UK_MIRR'],
  ['UK_TEL', 'The Telegraph'],
  ['The Telegraph', 'UK_TEL'],
  ['UK_TIME', 'The Times'],
  ['The Times', 'UK_TIME'],
  ['UK_MEN', 'Manchester Evening News'],
  ['Manchester Evening News', 'UK_MEN'],
  ['UK_INDP', 'The Independent'],
  ['The Independent', 'UK_INDP'],
  ['UK_PJ', 'The Press and Journal'],
  ['The Press and Journal', 'UK_PJ'],
  ['UK_ECOM', 'The Economist'],
  ['The Economist', 'UK_ECOM'],
  ['UK_KENT', 'Kentish Express'],
  ['Kentish Express', 'UK_KENT'],
  ['UK_OXM', 'Oxford Mail'],
  ['Oxford Mail', 'UK_OXM'],
  ['UK_GRDN', 'The Guardian'],
  ['The Guardian', 'UK_GRDN'],
  ['UK_CATH', 'The Catholic Herald'],
  ['The Catholic Herald', 'UK_CATH'],
  ['UK_DYST', 'Daily Star'],
  ['Daily Star', 'UK_DYST'],
  ['UK_EXPR', 'Daily Express'],
  ['Daily Express', 'UK_EXPR'],
  ['UK_EVSD', 'Evening Standard'],
  ['Evening Standard', 'UK_EVSD'],
  ['UK_FT', 'The Financial Times'],
  ['The Financial Times', 'UK_FT'],
  ['NZ_HRLD', 'The New Zealand Herald'],
  ['The New Zealand Herald', 'NZ_HRLD'],
  ['NZ_ODT', 'Otago Daily Times'],
  ['Otago Daily Times', 'NZ_ODT'],
  ['NZ_HBT', "Hawke's Bay Today"],
  ["Hawke's Bay Today", 'NZ_HBT'],
  ['NZ_AGO', 'Ashburton Guardian'],
  ['Ashburton Guardian', 'NZ_AGO'],
  ['NZ_BOPT', 'Bay of Plenty Times'],
  ['Bay of Plenty Times', 'NZ_BOPT'],
  ['NZ_TGH', 'The Gisborne Herald'],
  ['The Gisborne Herald', 'NZ_TGH'],
  ['NZ_TNA', 'The Northern Advocate'],
  ['The Northern Advocate', 'NZ_TNA'],
  ['NZ_OM', 'Oamaru Mail'],
  ['Oamaru Mail', 'NZ_OM'],
  ['NZ_WTA', 'Wairarapa Times-Age'],
  ['Wairarapa Times-Age', 'NZ_WTA'],
  ['NZ_WC', 'Whanganui Chronicle'],
  ['Whanganui Chronicle', 'NZ_WC'],
  ['NZ_RDP', 'Rotorua Daily Post'],
  ['Rotorua Daily Post', 'NZ_RDP'],
  ['NZ_GMS', 'Greymouth Star'],
  ['Greymouth Star', 'NZ_GMS'],
  ['OZ_AFR', 'Australian Financial Review'],
  ['Australian Financial Review', 'OZ_AFR'],
  ['OZ_DCN', 'Daily Cargo News'],
  ['Daily Cargo News', 'OZ_DCN'],
  ['OZ_TGL', 'Green Left'],
  ['Green Left', 'OZ_TGL'],
  ['OZ_TSP', 'The Saturday Paper'],
  ['The Saturday Paper', 'OZ_TSP'],
  ['OZ_CTVC', 'Catholic Voice'],
  ['Catholic Voice', 'OZ_CTVC'],
  ['OZ_CTYN', 'City News'],
  ['City News', 'OZ_CTYN'],
  ['OZ_RIOT', 'Riotact'],
  ['Riotact', 'OZ_RIOT'],
  ['OZ_ASNW', 'Alice Springs News'],
  ['Alice Springs News', 'OZ_ASNW'],
  ['OZ_ESS', 'The Eastern Shore Sun'],
  ['The Eastern Shore Sun', 'OZ_ESS'],
  ['OZ_GYGZ', 'The Glenorchy Gazette'],
  ['The Glenorchy Gazette', 'OZ_GYGZ'],
  ['OZ_CHC', 'Circular Head Chronicle'],
  ['Circular Head Chronicle', 'OZ_CHC'],
  ['OZ_KILC', 'King Is Land Courier'],
  ['King Is Land Courier', 'OZ_KILC'],
  ['OZ_HOBO', 'The Hobart Observerr'],
  ['The Hobart Observerr', 'OZ_HOBO'],
  ['US_ATDY', 'USA Today'],
  ['USA Today', 'US_ATDY'],
  ['US_WSJ', 'The Wall Street Journal'],
  ['The Wall Street Journal', 'US_WSJ'],
  ['US_NYT', 'The New York Times'],
  ['The New York Times', 'US_NYT'],
  ['US_LAT', 'Los Angeles Times'],
  ['Los Angeles Times', 'US_LAT'],
  ['US_NYP', 'New York Post'],
  ['New York Post', 'US_NYP'],
  ['US_MRCY', 'The Mercury News'],
  ['The Mercury News', 'US_MRCY'],
  ['US_CHGT', 'Chicago Tribune'],
  ['Chicago Tribune', 'US_CHGT'],
  ['US_HSTC', 'Houston Chronicle'],
  ['Houston Chronicle', 'US_HSTC'],
  ['US_PHIQ', 'The Philadelphia Inquirer'],
  ['The Philadelphia Inquirer', 'US_PHIQ'],
  ['US_NWDY', 'Newsday'],
  ['Newsday', 'US_NWDY'],
  ['US_DNVP', 'The Denver Post'],
  ['The Denver Post', 'US_DNVP'],
  ['US_STRT', 'Star Tribune'],
  ['Star Tribune', 'US_STRT'],
  ['US_CNN', 'CNN (International)'],
  ['CNN (International)', 'US_CNN'],
  ['US_FOX', 'FOX News (World)'],
  ['FOX News (World)', 'US_FOX'],
  ['US_AZCT', 'The Arizona Republic'],
  ['The Arizona Republic', 'US_AZCT'],
  ['US_DLLS', 'The Dallas Morning News'],
  ['The Dallas Morning News', 'US_DLLS'],
  ['US_TPD', 'The Plain Dealer'],
  ['The Plain Dealer', 'US_TPD'],
  ['US_CHST', 'Chicago Sun-Times'],
  ['Chicago Sun-Times', 'US_CHST'],
  ['US_DFR', 'Detroit Free Press'],
  ['Detroit Free Press', 'US_DFR'],
  ['US_ORGL', 'The Oregonian'],
  ['The Oregonian', 'US_ORGL'],
  ['US_SDTR', 'The San Diego Union-Tribune'],
  ['The San Diego Union-Tribune', 'US_SDTR'],
  ['US_SFC', 'San Francisco Chronicle'],
  ['San Francisco Chronicle', 'US_SFC'],
  ['US_BOSG', 'The Boston Globe'],
  ['The Boston Globe', 'US_BOSG'],
  ['US_STLT', 'St. Louis Post-Dispatch'],
  ['St. Louis Post-Dispatch', 'US_STLT'],
  ['US_TWNC', 'St. Paul Pioneer Press'],
  ['St. Paul Pioneer Press', 'US_TWNC'],
  ['US_RAFU', 'The Rafu Shimpo'],
  ['The Rafu Shimpo', 'US_RAFU'],
  ['US_ABC', 'ABC News'],
  ['ABC News', 'US_ABC'],
  ['US_CBS', 'CBS News'],
  ['CBS News', 'US_CBS'],
  ['US_NBC', 'NBC News'],
  ['NBC News', 'US_NBC'],
  ['US_GPB', 'Georgia Public Broadcasting'],
  ['Georgia Public Broadcasting', 'US_GPB'],
  ['US_MSN', 'MSNBC'],
  ['MSNBC', 'US_MSN'],
  ['US_NASA', 'NASA'],
  ['NASA', 'US_NASA'],
  ['US_CSPN', 'C-SPAN'],
  ['C-SPAN', 'US_CSPN'],
  ['US_HILL', 'The Hill'],
  ['The Hill', 'US_HILL'],
  ['TZ_CTZN', 'The Citizen'],
  ['The Citizen', 'TZ_CTZN'],
  ['TZ_DYNW', 'Daily News'],
  ['Daily News', 'TZ_DYNW'],
  ['TZ_HLEO', 'Daily News'],
  ['Daily News', 'TZ_HLEO'],
]);
